Add support for a build_docs_cmd
kinvolk/docs pull request #14
Opened 2021-02-23 23:25 UTC by illume

If there is a build_docs_cmd it will be run on that repo.

```yaml
    buildDocsCmd: "make docs"
```

With headlamp I'd like to generate some documentation with the storybook and typedoc tools. There's an open PR for that here: https://github.com/kinvolk/headlamp/pull/204 (when that is merged, I will update the branch on this PR to go back to the main branch).

2021-02-23 23:36 UTC, illume commented on docs/headlamp/_index.md
> +    branch: "typedoc"
Note, before merging this needs to be changed back to master.

2021-02-24 13:34 UTC, joaquimrocha requested changes

2021-02-24 13:34 UTC, joaquimrocha commented on docs/headlamp/_index.md
> +    buildDocsCmd: "make docs"
Let's call this `build_cmd` as we already have the docs context.

2021-02-24 13:34 UTC, joaquimrocha commented on tools/docs-fetcher.py
> +            subprocess.run(docs.get('buildDocsCmd'), shell=True, cwd=os.path.join(TOP_DIR_PATH, EXTERNAL_REPOS_DIR, repo_name))
I prefer not having to repeat the build key 3 times, so we should use a var for this. Same for the running path.

2021-07-14 06:38 UTC, closed without merging